pipeline {
    agent {label 'agent'}
    environment{
        WORKDIR = 'Monitoring'
    }
    stages{
        stage('Change Directory to where Compose file is located'){
            steps{
                sh 'cd /$WORKDIR'
                sh 'ls'
            }
        }
        stage('Build Docker stack'){
            steps {
                sh 'docker compose up'
            }
        }
        stage('Test Containers Are Running') {
            steps {
                sh '''
                # Check prometheus is running
                    if [ "$(docker inspect -f '{{.State.Running}}' prometheus)" != "true" ]; then
                        echo "prometheus container is NOT running!"
                        exit 1
                    fi

                # Check cadvisor is running
                    if [ "$(docker inspect -f '{{.State.Running}}' cadvisor)" != "true" ]; then
                        echo "cadvisor container is NOT running!"
                        exit 1
                    fi

                # Check node-exporter is running
                    if [ "$(docker inspect -f '{{.State.Running}}' node-exporter)" != "true" ]; then
                        echo "node-exporter container is NOT running!"
                        exit 1
                    fi

                echo "node-exporter, cAdvisor and prometheus are healthy."
                 '''
            }
        }
    }
}
